version: '3.8'

volumes:
  web_data:
    driver: local
  api_data:
    driver: local

services:
  web:
    image: web-template
    container_name: web-template
    build: web-template
    volumes:
      - web_data:/home
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - 5000
    restart: unless-stopped

  api:
    image: api-template
    container_name: api-template
    build: api-template
    volumes:
      - api_data:/home
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - 5000
    restart: unless-stopped

  proxy:
    image: nginx:latest
    container_name: nginx
    build: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./nginx/conf/mime.types:/etc/nginx/conf/mime.types:ro
      - ./nginx/logs:/var/log/nginx/logs:rw
    depends_on:
      - web
      - api
    ports:
      - 3000:3000
      - 4000:4000
    restart: unless-stopped
